################################
## Airflow Git-sync Key Secret
################################
apiVersion: v1
kind: Secret
metadata:
  name: airflow-ssh-secret
data:
  gitSshKey: '{{ .Values.dags.gitSync.sshKey }}'