kind: Service
apiVersion: v1
metadata:
  name: livy
  namespace: airflow
  labels:
    component: livy
spec:
  type: NodePort
  selector:
    component: livy
  ports:
    - name: livy-ui
      port: 8998
      targetPort: 8998
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: livy-config
  namespace: airflow
  labels:
    component: livy
data:
  livy.conf: |-
    livy.spark.master = k8s://https://kubernetes.default:443
    livy.spark.deploy-mode = cluster
    livy.file.local-dir-whitelist = /
    livy.server.port = 8998
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: livy-st
  namespace: airflow
  labels:
    component: livy
spec:
  serviceName: livy
  replicas: 1
  selector:
    matchLabels:
      component: livy
  template:
    metadata:
      labels:
        component: livy
    spec:
      securityContext:
        runAsUser: 0
        fsGroup: 0
      containers:
        - name: livy
          image: $LIVY_IMAGE
          imagePullPolicy: Always
          args:
            - bin/livy-server
          volumeMounts:
            - name: config
              mountPath: /conf/livy.conf
              subPath: livy.conf
              readOnly: true
            - name: logs
              mountPath: /logs
          ports:
            - name: livy-ui
              containerPort: 8998
          env:
              - name: LIVY_LOG_DIR
                value: "/logs"
              - name: LIVY_CONF_DIR
                value: "/conf"
      volumes:
        - name: config
          configMap:
            name: livy-config
        - name: logs
          emptyDir: {}
